'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_histprivate
    Public Property histseq As Long
    Public Property companycd As String
    Public Property companybranchno As Nullable(Of Integer)
    Public Property staffcd As String
    Public Property sts As String
    Public Property postno As String
    Public Property prefecturescd As String
    Public Property address1 As String
    Public Property address2 As String
    Public Property tel As String
    Public Property fax As String
    Public Property sendpostno As String
    Public Property sendprefecturescd As String
    Public Property sendaddress1 As String
    Public Property sendaddress2 As String
    Public Property sendtel As String
    Public Property sendfax As String
    Public Property mail As String
    Public Property belongcd1 As String
    Public Property belongname1 As String
    Public Property belongname2 As String
    Public Property notes As String
    Public Property vipflg As String
    Public Property abnormalflg As Nullable(Of Integer)
    Public Property abnormalcount As Nullable(Of Integer)
    Public Property privateno1usercd As String
    Public Property privateno1datetime As Nullable(Of Date)
    Public Property privateno2usercd As String
    Public Property privateno2datetime As Nullable(Of Date)
    Public Property privatenocusercd As String
    Public Property privatenocdatetime As Nullable(Of Date)
    Public Property expusercd As String
    Public Property expdatetime As Nullable(Of Date)
    Public Property printflg As Nullable(Of Integer)
    Public Property sendpostnoflg As Nullable(Of Integer)
    Public Property delflg As Nullable(Of Integer)
    Public Property deldatetime As Nullable(Of Date)
    Public Property delusercd As String
    Public Property adddatetime As Nullable(Of Date)
    Public Property addjusercd As String
    Public Property upddatetime As Nullable(Of Date)
    Public Property updusercd As String
    Public Property terminalcd As String

End Class
