'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_histcompany
    Public Property histseq As Long
    Public Property companycd As String
    Public Property companybranchno As Nullable(Of Integer)
    Public Property companyname As String
    Public Property companybranchname As String
    Public Property contactfamilyname As String
    Public Property contactfamilynamekana As String
    Public Property contactpostno As String
    Public Property contactprefecturescd As String
    Public Property contactaddress1 As String
    Public Property contactaddress2 As String
    Public Property contacttel As String
    Public Property contactfax As String
    Public Property contactmail As String
    Public Property contactbelongname1 As String
    Public Property contactbelongname2 As String
    Public Property contactnotes As String
    Public Property trusteeflg01 As Nullable(Of Integer)
    Public Property trusteeflg02 As Nullable(Of Integer)
    Public Property trusteeflg03 As Nullable(Of Integer)
    Public Property trusteeflg04 As Nullable(Of Integer)
    Public Property trusteeflg05 As Nullable(Of Integer)
    Public Property trusteeflg06 As Nullable(Of Integer)
    Public Property trusteeflg07 As Nullable(Of Integer)
    Public Property trusteeflg08 As Nullable(Of Integer)
    Public Property trusteeflg09 As Nullable(Of Integer)
    Public Property trusteeflg10 As Nullable(Of Integer)
    Public Property trusteeflg11 As Nullable(Of Integer)
    Public Property trusteeflg12 As Nullable(Of Integer)
    Public Property trusteeflg13 As Nullable(Of Integer)
    Public Property trusteeflg14 As Nullable(Of Integer)
    Public Property trusteeflg15 As Nullable(Of Integer)
    Public Property trusteeflg16 As Nullable(Of Integer)
    Public Property trusteeflg17 As Nullable(Of Integer)
    Public Property trusteeflg18 As Nullable(Of Integer)
    Public Property trusteeflg19 As Nullable(Of Integer)
    Public Property trusteeflg20 As Nullable(Of Integer)
    Public Property delivschdate As Nullable(Of Date)
    Public Property delivdate As Nullable(Of Date)
    Public Property delschdate As Nullable(Of Date)
    Public Property deldate As Nullable(Of Date)
    Public Property delflg As Nullable(Of Integer)
    Public Property deldatetime As Nullable(Of Date)
    Public Property delusercd As String
    Public Property adddatetime As Nullable(Of Date)
    Public Property addjusercd As String
    Public Property upddatetime As Nullable(Of Date)
    Public Property updusercd As String
    Public Property terminalcd As String

End Class
