'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_importlog
    Public Property seq As Long
    Public Property companycd As String
    Public Property companybranchno As Nullable(Of Integer)
    Public Property companyname As String
    Public Property companybranchname As String
    Public Property impdatetime As Nullable(Of Date)
    Public Property impusercd As String
    Public Property csvfile As Byte()
    Public Property filename As String
    Public Property imptype As Nullable(Of Integer)
    Public Property filetype As Nullable(Of Integer)
    Public Property errflg As Nullable(Of Integer)
    Public Property adddatetime As Nullable(Of Date)
    Public Property addjusercd As String
    Public Property terminalcd As String

End Class
