'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class w_company
    Public Property seq As Long
    Public Property line As Long
    Public Property companycd As String
    Public Property companybranchno As String
    Public Property companyname As String
    Public Property companybranchname As String
    Public Property contactfamilyname As String
    Public Property contactfamilynamekana As String
    Public Property contactpostno As String
    Public Property contactprefecturescd As String
    Public Property contactaddress1 As String
    Public Property contactaddress2 As String
    Public Property contacttel As String
    Public Property contactfax As String
    Public Property contactmail As String
    Public Property contactbelongname1 As String
    Public Property contactbelongname2 As String
    Public Property contactnotes As String
    Public Property trusteeflg01 As String
    Public Property trusteeflg02 As String
    Public Property trusteeflg03 As String
    Public Property trusteeflg04 As String
    Public Property trusteeflg05 As String
    Public Property trusteeflg06 As String
    Public Property trusteeflg07 As String
    Public Property trusteeflg08 As String
    Public Property trusteeflg09 As String
    Public Property trusteeflg10 As String
    Public Property trusteeflg11 As String
    Public Property trusteeflg12 As String
    Public Property delivschdate As String
    Public Property delschdate As String

End Class
