'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class m_appxauth
    Public Property authoritycd As String
    Public Property appcd As String
    Public Property viewauthflg As Nullable(Of Integer)
    Public Property updauthflg As Nullable(Of Integer)
    Public Property viewpriority As Nullable(Of Integer)
    Public Property adddatetime As Nullable(Of Date)
    Public Property addjusercd As String
    Public Property upddatetime As Nullable(Of Date)
    Public Property updusercd As String
    Public Property terminalcd As String

End Class
