'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_bienap
    Public Property somay As String
    Public Property tenkhachhang As String
    Public Property tentrambienap As String
    Public Property diachi As String
    Public Property tinhchat_kh As String
    Public Property tinhchat_cc As String
    Public Property loaitba_bet As String
    Public Property loaitba_x As String
    Public Property loaitba_t As String
    Public Property loaitba_mc As String
    Public Property loaitba_k As String
    Public Property loaitba_dau As String
    Public Property loaitba_kho As String
    Public Property kva As Nullable(Of Integer)
    Public Property nuocsanxuat As String
    Public Property namsanxuat As Nullable(Of Integer)
    Public Property tskh_mba As String
    Public Property tskh_tucaudao As String
    Public Property nguoicapnhat As String
    Public Property lo As String
    Public Property ngaycapnhat As Nullable(Of Date)
    Public Property ngaythinghiem As Nullable(Of Date)

End Class
