'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_bienapimport
    Public Property stt As Long
    Public Property ngaynhap As Nullable(Of System.TimeSpan)
    Public Property nguoinhap As String
    Public Property tenfile As String
    Public Property delflg As Nullable(Of Integer)
    Public Property deldatetime As Nullable(Of System.TimeSpan)
    Public Property adddatetime As Nullable(Of System.TimeSpan)
    Public Property nguoithem As String
    Public Property exceldata As Byte()

End Class
