'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class t_family
    Public Property companycd As String
    Public Property companybranchno As Integer
    Public Property staffcd As String
    Public Property familyno As Integer
    Public Property familyname As String
    Public Property familynamekana As String
    Public Property birthdate As Nullable(Of Date)
    Public Property sex As Nullable(Of Integer)
    Public Property insuredflg As Nullable(Of Integer)
    Public Property delflg As Nullable(Of Integer)
    Public Property deldatetime As Nullable(Of Date)
    Public Property delusercd As String
    Public Property adddatetime As Nullable(Of Date)
    Public Property addjusercd As String
    Public Property upddatetime As Nullable(Of Date)
    Public Property updusercd As String
    Public Property terminalcd As String

End Class
