'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class w_family
    Public Property seq As Long
    Public Property line As Long
    Public Property companycd As String
    Public Property companybranchno As String
    Public Property staffcd As String
    Public Property familyname As String
    Public Property familynamekana As String
    Public Property birthdate As String
    Public Property sex As String
    Public Property insuredflg As String

End Class
