'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class w_private
    Public Property seq As Long
    Public Property line As Long
    Public Property companycd As String
    Public Property companybranchno As String
    Public Property staffcd As String
    Public Property familyname As String
    Public Property familynamekana As String
    Public Property birthdate As String
    Public Property sex As String
    Public Property postno As String
    Public Property prefecturescd As String
    Public Property address1 As String
    Public Property address2 As String
    Public Property tel As String
    Public Property fax As String
    Public Property sendpostno As String
    Public Property sendprefecturescd As String
    Public Property sendaddress1 As String
    Public Property sendaddress2 As String
    Public Property sendtel As String
    Public Property sendfax As String
    Public Property mail As String
    Public Property belongcd1 As String
    Public Property belongname1 As String
    Public Property belongname2 As String
    Public Property vipflg As String

End Class
