'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class w_privateno
    Public Property seq As Long
    Public Property companycd As String
    Public Property companybranchno As Integer
    Public Property staffcd As String
    Public Property familyno As Integer
    Public Property companyname As String
    Public Property sendpostno As String
    Public Property sendpostnomark As String
    Public Property sendname As String
    Public Property sendaddress1 As String
    Public Property sendaddress2 As String
    Public Property familyname As String
    Public Property familynamekana As String
    Public Property insuredflg As String
    Public Property sex As String
    Public Property birthdate As String
    Public Property printdate As String
    Public Property customerbarcode As String
    Public Property barcode As String
    Public Property contactbelongname As String
    Public Property contactaddress As String
    Public Property contacttel As String
    Public Property address As String
    Public Property sendpostsort As Nullable(Of Integer)
    Public Property sumpostno As String
    Public Property printflg As Nullable(Of Integer)

End Class
