'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class w_sumpostno
    Public Property seq As Long
    Public Property companycd As String
    Public Property companybranchno As Integer
    Public Property staffcd As String
    Public Property sendpostsort As Nullable(Of Long)
    Public Property sendpostno As String
    Public Property sumpostno As String
    Public Property printflg As Nullable(Of Integer)
    Public Property sumpostnocount As Nullable(Of Long)

End Class
